### ISSUE TITLE
bug: circles no longer collide with each other??

### ISSUE THREAD

**Issue by dragoncoder047** [kaplayjs/kaplay#834]
### Bug Description

In a16 the circles collide with each other. In a17 they don't (check the kaplayground version dropdown)

### Version

4000.0.0-alpha.17

### Playground Link

https://play.kaplayjs.com/?code=eJzLTizISazU0LTm4ipOLXEvSizLLKnUMDQwMAAJJaakaERzKQBBQX4xSFRHAUho6oCFkjOLknNSNYxg%2FMSi1EQNKDspP6VSo1ohszi4JLEkM9lKoaSoNFWhFigbi8Ncok0Fm8HFlZKaVJqul5lXXJCaXKJgC7bAmgsArnI1YQ%3D%3D&version=4000.0.0-alpha.16

### Summary

- [ ] Fixed in v4000
- [ ] Fixed in v3001

**Comment by mflerackers** [comment]
@lajbel You already forgot I fixed this?

**Comment by lajbel** [comment]
Why is not closed

**Comment by dragoncoder047** [comment]
It isn't fixed on master, it's fixed on the prefabs branch of all places

**Comment by mflerackers** [comment]
Yeah, I know. It'll be fixed once that's merged.
